// <auto-generated />
using System;
using CDExellentAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDExellentAPI.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    [Migration("20241223170925_Update_Table_Distritor_Last1")]
    partial class Update_Table_Distritor_Last1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CDExellentAPI.Entities.Area", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Distributor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SalesId")
                        .HasColumnType("int");

                    b.Property<int>("SalesManagementId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("AreaId");

                    b.HasIndex("SalesManagementId");

                    b.ToTable("Distributor");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Guest", b =>
                {
                    b.Property<int>("VisitPlanId")
                        .HasColumnType("int");

                    b.Property<int>("GuestUserId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAccept")
                        .HasColumnType("bit");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitPlanId", "GuestUserId");

                    b.HasIndex("GuestUserId");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.PlanStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("PlanStatus");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AssigneeFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReporterFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<int>("RepoterId")
                        .HasColumnType("int");

                    b.Property<int?>("StarRate")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VisitPlanId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("PlanUserId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("TaskStatusId");

                    b.HasIndex("VisitPlanId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.TaskStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TaskStatus");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Title", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.TypeDate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TypeDate");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AreaId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TitleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.VisitPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PlanUserId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TypeDateId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DistributorId");

                    b.HasIndex("PlanStatusId");

                    b.HasIndex("PlanUserId");

                    b.HasIndex("TypeDateId");

                    b.ToTable("VisitPlan");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Distributor", b =>
                {
                    b.HasOne("CDExellentAPI.Entities.Area", "Area")
                        .WithMany("Distributors")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.User", "SalesManagement")
                        .WithMany("Distributors")
                        .HasForeignKey("SalesManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("SalesManagement");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Guest", b =>
                {
                    b.HasOne("CDExellentAPI.Entities.User", "GuestUser")
                        .WithMany("Guests")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.VisitPlan", "VisitPlan")
                        .WithMany("Guests")
                        .HasForeignKey("VisitPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GuestUser");

                    b.Navigation("VisitPlan");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Task", b =>
                {
                    b.HasOne("CDExellentAPI.Entities.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.User", "PlanUser")
                        .WithMany("PlannedTasks")
                        .HasForeignKey("PlanUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.User", "Reporter")
                        .WithMany("ReportedTasks")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.TaskStatus", "TaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.VisitPlan", "VisitPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("VisitPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("PlanUser");

                    b.Navigation("Reporter");

                    b.Navigation("TaskStatus");

                    b.Navigation("VisitPlan");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Title", b =>
                {
                    b.HasOne("CDExellentAPI.Entities.Category", "Category")
                        .WithMany("Titles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.User", b =>
                {
                    b.HasOne("CDExellentAPI.Entities.Area", "Area")
                        .WithMany("Users")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.User", "Manager")
                        .WithMany("Managers")
                        .HasForeignKey("ManagerId");

                    b.HasOne("CDExellentAPI.Entities.Title", "Title")
                        .WithMany("Users")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Manager");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.VisitPlan", b =>
                {
                    b.HasOne("CDExellentAPI.Entities.Distributor", "Distributor")
                        .WithMany("VisitPlans")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.PlanStatus", "PlanStatus")
                        .WithMany("VisitPlans")
                        .HasForeignKey("PlanStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.User", "PlanUser")
                        .WithMany("VisitPlans")
                        .HasForeignKey("PlanUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CDExellentAPI.Entities.TypeDate", "TypeDate")
                        .WithMany("Plans")
                        .HasForeignKey("TypeDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("PlanStatus");

                    b.Navigation("PlanUser");

                    b.Navigation("TypeDate");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Area", b =>
                {
                    b.Navigation("Distributors");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Category", b =>
                {
                    b.Navigation("Titles");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Distributor", b =>
                {
                    b.Navigation("VisitPlans");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.PlanStatus", b =>
                {
                    b.Navigation("VisitPlans");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.TaskStatus", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.Title", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.TypeDate", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Distributors");

                    b.Navigation("Guests");

                    b.Navigation("Managers");

                    b.Navigation("PlannedTasks");

                    b.Navigation("ReportedTasks");

                    b.Navigation("VisitPlans");
                });

            modelBuilder.Entity("CDExellentAPI.Entities.VisitPlan", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
